### 회원가입
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"usertest",
  "password":"12345",
  "passwordConfirm":"12345",
  "nickname": "coconut"
}

### 회원가입 - 중복된 id
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"usertest3",
  "password":"12345",
  "passwordConfirm":"12345",
  "nickname": "papapa"
}

### 회원가입 - 중복된 닉네임
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"yty",
  "password":"12345",
  "passwordConfirm":"12345",
  "nickname": "coconut"
}

### 회원가입 - 비밀번호 불일치
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"yty",
  "password":"123456",
  "passwordConfirm":"123457",
  "nickname": "gg"
}

### 로그인 - 없는 사용자 -> MEMBER NOT FOUND
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"usertes",
  "password":"12345"
}

### 로그인 - 잘못된 비밀번호 -> MEMBER NOT FOUND
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"usertest3",
  "password":"12345!!"
}

### 로그인
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"usertest3",
  "password":"123456"
}

### 회원1 답 작성
POST http://localhost:8080/auth/interview/1/myanswer
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MDAwNzIsImV4cCI6MTY2MjYwMTg3Mn0.nF0RIr4RXbUoQ0CnWCBq3Qc4SrjuNPS--PEcEXmALk4
Content-Type: application/json

{
  "content": "자바는 객체지향 언어이다.",
  "publicTF": true
}

####### 글쓰기 - access토큰 안보냄 -> IVALID LOGIN
POST http://localhost:8080/auth/interview/1/myanswer
Content-Type: application/json

{
  "content": "자바는 객체지향 언어이다.",
  "publicTF": true
}

#### 찜하기 ####
POST http://localhost:8080/auth/interview/1/like
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU2MzAsImV4cCI6MTY2MjYxNTkzMH0._uy7Om2UN-mj6moS_vL5Enl0hCDFZyUL6LpCkBevlQw

####### 찜하기 - bearer type안쓰고 access토큰 보내기 -> INVALD ACCESS TOKEN
POST http://localhost:8080/auth/interview/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE
#Content-Type: application/json
#
#{
#  "interviewId": 1,
#  "content": "자바는 객체지향 언어이다.",
#  "ispublic": true
#}

####### 찜하기 - 잘못된 access토큰 보내기 -> INVALD ACCESS TOKEN
POST http://localhost:8080/auth/interview/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydG2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE
Content-Type: application/json

//{
//  "interviewId": 1,
//  "content": "자바는 객체지향 언어이다.",
//  "ispublic": true
//}


####### access토큰 만료 후 찜하기 -> EXPIRED ACCESS TOKEN
POST http://localhost:8080/auth/interview/1
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE
Content-Type: application/json

//{
//  "interviewId": 1,
//  "content": "자바는 객체지향 언어이다.",
//  "ispublic": true
//}

###### reissue - 리프레쉬 토큰 안보냄 -> NEED REFRESH TOKEN
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE

###### reissue - 리프레쉬 token type 빼고 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTg5NH0.gPnVE4ucWn6iPrzDIs2lfG46OTShGQ7LFYIPEIObKnY

###### reissue - 유효하지 않은 리프레쉬 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE
Refresh-Token: BEARER eyJhbGcGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTg5NH0.gPnVE4ucWn6iPrzDIs2lfG46OTShGQ7LFYIPEIObKnY

###### reissue - access토큰 안보냄 -> NEED ACCESS TOKEN
POST http://localhost:8080/member/reissue
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTg5NH0.gPnVE4ucWn6iPrzDIs2lfG46OTShGQ7LFYIPEIObKnY

###### reissue - access토큰 type 빼고 보냄 -> INVALID ACCESS TOKEN
POST http://localhost:8080/member/reissue
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTg5NH0.gPnVE4ucWn6iPrzDIs2lfG46OTShGQ7LFYIPEIObKnY

###### reissue - 유효하지 않은 access토큰 보냄 -> IVALID ACCESS TOKEN
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTg5NH0.gPnVE4ucWn6iPrzDIs2lfG46OTShGQ7LFYIPEIObKnY

###### reissue 성공
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTg5NH0.gPnVE4ucWn6iPrzDIs2lfG46OTShGQ7LFYIPEIObKnY

###### reissue - 만료된 리프레쉬 토큰 보냄 -> EXPIRED REFRESH TOKEN
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTU5NH0.0UddsNryX2NbL6nNLtWfJKDScaEBW7YEtPkHfHM4-QE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTUyOTQsImV4cCI6MTY2MjYxNTg5NH0.gPnVE4ucWn6iPrzDIs2lfG46OTShGQ7LFYIPEIObKnY


### 로그인
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"usertest3",
  "password":"123456"
}

#### 찜하기 ####
POST http://localhost:8080/auth/interview/1/like
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTIwNjQsImV4cCI6MTY2MjYxMjI0NH0.8nsgKVXyTvEDUnlKXNH_Zvmc1G3Jgi8RdWWl12JwJdk

### 로그아웃 - access 토큰 안보냄 -> INVALID LOGIN
POST http://localhost:8080/auth/member/logout
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjU0NX0.aKIPU-UMROqZqUS6VHSgPRalm4907ErAWVIBLBcCI4U

### 로그아웃 - type뺀 access 토큰 보냄 -> INVALID ACCESS TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjI0NX0.NHJW_o9rpyADrcpzvuzQYFF8I8vh0XyF33lSBcHEbKE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjU0NX0.aKIPU-UMROqZqUS6VHSgPRalm4907ErAWVIBLBcCI4U

### 로그아웃 - 유효하지 않은 access 토큰 보냄 -> INVALID ACCESS TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1Ni][p[]0-LCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjI0NX0.NHJW_o9rpyADrcpzvuzQYFF8I8vh0XyF33lSBcHEbKE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjU0NX0.aKIPU-UMROqZqUS6VHSgPRalm4907ErAWVIBLBcCI4U

### 로그아웃 - 리프레쉬 토큰 안보냄 -> NEED REFRESH TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjI0NX0.NHJW_o9rpyADrcpzvuzQYFF8I8vh0XyF33lSBcHEbKE


### 로그아웃 - 리프레쉬 token type 빼고 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjI0NX0.NHJW_o9rpyADrcpzvuzQYFF8I8vh0XyF33lSBcHEbKE
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjU0NX0.aKIPU-UMROqZqUS6VHSgPRalm4907ErAWVIBLBcCI4U

### 로그아웃 - 유효하지 않은 리프레쉬 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjI0NX0.NHJW_o9rpyADrcpzvuzQYFF8I8vh0XyF33lSBcHEbKE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2N33434jI2MTU5NDUsImV4cCI6MTY2MjYxNjU0NX0.aKIPU-UMROqZqUS6VHSgPRalm4907ErAWVIBLBcCI4U

### 로그아웃 - 만료된 access 토큰 보냄 -> EXPIRED ACCESS TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjI0NX0.NHJW_o9rpyADrcpzvuzQYFF8I8vh0XyF33lSBcHEbKE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjU0NX0.aKIPU-UMROqZqUS6VHSgPRalm4907ErAWVIBLBcCI4U

###### reissue 성공
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjI0NX0.NHJW_o9rpyADrcpzvuzQYFF8I8vh0XyF33lSBcHEbKE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjU0NX0.aKIPU-UMROqZqUS6VHSgPRalm4907ErAWVIBLBcCI4U

### 로그아웃 - 만료된 Refresh 토큰 보냄 (access토큰은 만료 안됨) -> 로그아웃 됨
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjI0NX0.NHJW_o9rpyADrcpzvuzQYFF8I8vh0XyF33lSBcHEbKE
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDMiLCJpYXQiOjE2NjI2MTU5NDUsImV4cCI6MTY2MjYxNjU0NX0.aKIPU-UMROqZqUS6VHSgPRalm4907ErAWVIBLBcCI4U


### 회원가입2
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"ky",
  "password":"1111",
  "passwordConfirm":"1111",
  "nickname": "papaya"
}

### 회원2 로그인
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"ky",
  "password":"1111"
}

### 회원1 로그인
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"usertest3",
  "password":"123456"
}

### 회원2 로그아웃 - 사용자 토큰과 일치하지 않은 리프레쉬 토큰(회원1 토큰) 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJpYXQiOjE2NjI0Nzg1NzAsImV4cCI6MTY2MjQ3ODg3MH0.AmngOutaVwXAkSM8nssmVycu7DdYDaEw1U7DmQWrxYU
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0Nzg2MDcsImV4cCI6MTY2MjQ3OTIwN30.SHt26NIJO7tsNOO67bP7Nqwfxx__Tk5Qj-uLq4YZXhw


###  회원2 로그아웃
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJpYXQiOjE2NjI0Nzg1NzAsImV4cCI6MTY2MjQ3ODg3MH0.AmngOutaVwXAkSM8nssmVycu7DdYDaEw1U7DmQWrxYU
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJpYXQiOjE2NjI0Nzg1NzAsImV4cCI6MTY2MjQ3OTE3MH0.jpc3AWIFz2W8ZuUF0bBL7Mvp40PoPSXDpoYRJy_dIHo