### 회원가입
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"kiyeon",
  "password":"12345",
  "passwordConfirm":"12345",
  "nickname": "coconut"
}

### 회원가입 - 중복된 id
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"kiyeon",
  "password":"12345",
  "passwordConfirm":"12345",
  "nickname": "papapa"
}

### 회원가입 - 중복된 닉네임
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"usertest2",
  "password":"12345",
  "passwordConfirm":"12345",
  "nickname": "coconut"
}

### 회원가입 - 비밀번호 불일치
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"usertest3",
  "password":"123456",
  "passwordConfirm":"123457",
  "nickname": "coconut2"
}

### 로그인 - 없는 사용자 -> MEMBER NOT FOUND
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"kiyeon2",
  "password":"12345"
}

### 로그인 - 잘못된 비밀번호 -> MEMBER NOT FOUND
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"kiyeon",
  "password":"12345"
}

### 회원1 답 작성
POST http://localhost:8080/auth/interview/1
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3NzY0N30.-g4w8dkKr8V5QQen5YusP_FSJjROP_WXnOohL3H0pEI
Content-Type: application/json

{
  "interviewId": 1,
  "content": "자바는 객체지향 언어이다.",
  "ispublic": true
}

####### 글쓰기 - access토큰 안보냄 -> IVALID LOGIN
POST http://localhost:8080/auth/interview/1
Content-Type: application/json

{
  "interviewId": 1,
  "content": "자바는 객체지향 언어이다.",
  "ispublic": true
}

####### 글쓰기 - bearer type안쓰고 access토큰 보내기 -> INVALD ACCESS TOKEN
POST http://localhost:8080/auth/interview/1
Authorization: Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3NzY0N30.-g4w8dkKr8V5QQen5YusP_FSJjROP_WXnOohL3H0pEI
Content-Type: application/json

{
  "interviewId": 1,
  "content": "자바는 객체지향 언어이다.",
  "ispublic": true
}

####### 글쓰기 - 잘못된 access토큰 보내기 -> INVALD ACCESS TOKEN
POST http://localhost:8080/auth/interview/1
Authorization: Authorization: BEARER eyJhbGciOiJIUI6MTY2MjQ3NzY0N30.-g4w8dkKr8V5QQen5YusP_FSJjROP_WXnOohL3H0pEI
Content-Type: application/json

{
  "interviewId": 1,
  "content": "자바는 객체지향 언어이다.",
  "ispublic": true
}


####### access토큰 만료 후 글쓰기 -> EXPIRED ACCESS TOKEN
POST http://localhost:8080/auth/interview/1
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdCIsImlhdCI6MTY2MjQyOTU2NSwiZXhwIjoxNjYyNDI5Njg1fQ.ZwFkpEzYR7j711I02CaaswAv-pIy6BSPeHOwvR8i1Ck
Content-Type: application/json

{
  "interviewId": 1,
  "content": "자바는 객체지향 언어이다.",
  "ispublic": true
}

###### reissue - 리프레쉬 토큰 안보냄 -> NEED REFRESH TOKEN
POST http://localhost:8080/member/reissue
Authorization: Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3NzY0N30.-g4w8dkKr8V5QQen5YusP_FSJjROP_WXnOohL3H0pEI

###### reissue - 리프레쉬 token type 빼고 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3NzY0N30.-g4w8dkKr8V5QQen5YusP_FSJjROP_WXnOohL3H0pEI
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3Nzk0N30.orh0dhK8oQY4hJe1eueAcp1vSwtJnowFnBrhd4mdP7k

###### reissue - 유효하지 않은 리프레쉬 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3NzY0N30.-g4w8dkKr8V5QQen5YusP_FSJjROP_WXnOohL3H0pEI
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczdhK8oQY4hJe1eueAcp1vSwtJnowFnBrhd4mdP7k

###### reissue - access토큰 안보냄 -> NEED ACCESS TOKEN
POST http://localhost:8080/member/reissue
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3Nzk0N30.orh0dhK8oQY4hJe1eueAcp1vSwtJnowFnBrhd4mdP7k

###### reissue - access토큰 type 빼고 보냄 -> INVALID ACCESS TOKEN
POST http://localhost:8080/member/reissue
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3NzY0N30.-g4w8dkKr8V5QQen5YusP_FSJjROP_WXnOohL3H0pEI
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3Nzk0N30.orh0dhK8oQY4hJe1eueAcp1vSwtJnowFnBrhd4mdP7k

###### reissue - 유효하지 않은 access토큰 보냄 -> IVALID ACCESS TOKEN
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTr8V5QQen5YusP_FSJjROP_WXnOohL3H0pEI
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3Nzk0N30.orh0dhK8oQY4hJe1eueAcp1vSwtJnowFnBrhd4mdP7k

###### reissue 성공
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3NzY0N30.-g4w8dkKr8V5QQen5YusP_FSJjROP_WXnOohL3H0pEI
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3Nzk0N30.orh0dhK8oQY4hJe1eueAcp1vSwtJnowFnBrhd4mdP7k

###### reissue - 만료된 리프레쉬 토큰 보냄 -> EXPIRED REFRESH TOKEN
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0Nzc2MjcsImV4cCI6MTY2MjQ3NzkyN30.8fVMyxtFgvVGJhmz4ygfHNy95qEtzstxLtexCIXahZ8
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzczNDcsImV4cCI6MTY2MjQ3Nzk0N30.orh0dhK8oQY4hJe1eueAcp1vSwtJnowFnBrhd4mdP7k


### 로그인
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"kiyeon",
  "password":"12345"
}

### 로그아웃 - access 토큰 안보냄 -> INVALID LOGIN
POST http://localhost:8080/auth/member/logout
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODYxNX0.BWrveToWSoZpWLVmcJp17i6z2JUXO8q5h4_qaXX474I

### 로그아웃 - type뺀 access 토큰 보냄 -> INVALID ACCESS TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODMxNX0.TEZgpMLAd9_SEvliIuowk_hSjQYbX15NlPkYgI7Q6Tk
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODYxNX0.BWrveToWSoZpWLVmcJp17i6z2JUXO8q5h4_qaXX474I

### 로그아웃 - 유효하지 않은 access 토큰 보냄 -> INVALID ACCESS TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODMxNX0.TEZgpMLAd9_SEvliIuowk_hSjQYbX15NlPkYgI7Q6Tk
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODYxNX0.BWrveToWSoZpWLVmcJp17i6z2JUXO8q5h4_qaXX474I

### 로그아웃 - 리프레쉬 토큰 안보냄 -> NEED REFRESH TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODMxNX0.TEZgpMLAd9_SEvliIuowk_hSjQYbX15NlPkYgI7Q6Tk


### 로그아웃 - 리프레쉬 token type 빼고 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODMxNX0.TEZgpMLAd9_SEvliIuowk_hSjQYbX15NlPkYgI7Q6Tk
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODYxNX0.BWrveToWSoZpWLVmcJp17i6z2JUXO8q5h4_qaXX474I

### 로그아웃 - 유효하지 않은 리프레쉬 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODMxNX0.TEZgpMLAd9_SEvliIuowk_hSjQYbX15NlPkYgI7Q6Tk
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraLVmcJp17i6z2JUXO8q5h4_qaXX474I

### 로그아웃 - 만료된 access 토큰 보냄 -> EXPIRED ACCESS TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODMxNX0.TEZgpMLAd9_SEvliIuowk_hSjQYbX15NlPkYgI7Q6Tk
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODYxNX0.BWrveToWSoZpWLVmcJp17i6z2JUXO8q5h4_qaXX474I

###### reissue 성공
POST http://localhost:8080/member/reissue
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODMxNX0.TEZgpMLAd9_SEvliIuowk_hSjQYbX15NlPkYgI7Q6Tk
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODYxNX0.BWrveToWSoZpWLVmcJp17i6z2JUXO8q5h4_qaXX474I

### 로그아웃 - 만료된 Refresh 토큰 보냄 (access토큰은 만료 안됨) -> 로그아웃 됨
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgzMzIsImV4cCI6MTY2MjQ3ODYzMn0.o01nCFK3KoUpFxvW-8Y5yQGa_pFVaWzdBRWw0IhCfRg
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0NzgwMTUsImV4cCI6MTY2MjQ3ODYxNX0.BWrveToWSoZpWLVmcJp17i6z2JUXO8q5h4_qaXX474I


### 회원가입2
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username":"usertest2",
  "password":"123456",
  "passwordConfirm":"123456",
  "nickname": "papaya"
}

### 회원2 로그인
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"usertest2",
  "password":"123456"
}

### 회원1 로그인
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "username":"kiyeon",
  "password":"12345"
}

### 회원2 로그아웃 - 사용자 토큰과 일치하지 않은 리프레쉬 토큰(회원1 토큰) 보냄 -> IVALID REFRESH TOKEN
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJpYXQiOjE2NjI0Nzg1NzAsImV4cCI6MTY2MjQ3ODg3MH0.AmngOutaVwXAkSM8nssmVycu7DdYDaEw1U7DmQWrxYU
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraXllb24iLCJpYXQiOjE2NjI0Nzg2MDcsImV4cCI6MTY2MjQ3OTIwN30.SHt26NIJO7tsNOO67bP7Nqwfxx__Tk5Qj-uLq4YZXhw


###  회원2 로그아웃
POST http://localhost:8080/auth/member/logout
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJpYXQiOjE2NjI0Nzg1NzAsImV4cCI6MTY2MjQ3ODg3MH0.AmngOutaVwXAkSM8nssmVycu7DdYDaEw1U7DmQWrxYU
Refresh-Token: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VydGVzdDIiLCJpYXQiOjE2NjI0Nzg1NzAsImV4cCI6MTY2MjQ3OTE3MH0.jpc3AWIFz2W8ZuUF0bBL7Mvp40PoPSXDpoYRJy_dIHo